name: Publish Web App
on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Workloads
        run: dotnet workload restore src/dndspellviewercrossplatform.Browser/dndspellviewercrossplatform.Browser.csproj
     
      - name: Minify Spell Data
        run: |
          if [ -f "src/dndspellviewercrossplatform/assets/spells.json" ]; then
            jq -c . src/dndspellviewercrossplatform/assets/spells.json > minified.json
            mv minified.json src/dndspellviewercrossplatform/assets/spells.json
            echo "Spells.json minified successfully."
          else
            echo "spells.json not found, skipping minification."
          fi

      - name: Publish Web
        run: dotnet publish src/dndspellviewercrossplatform.Browser/dndspellviewercrossplatform.Browser.csproj -c Release -o ./web-build
        
      - name: Prepare Docs Folder
        run: |
          mkdir -p docs
          rm -rf docs/*
          cp -r ./web-build/wwwroot/* docs/
          touch docs/.nojekyll

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update web app in docs folder with .nojekyll" || echo "No changes to commit"
          git push
